version: '2.3'

services:
    SITL:
        image: vector_guidance/ros1:v1.0
        network_mode: "host"
        privileged: true
        command: ./ros_launch_sitl.sh
        environment:
            DISPLAY: ${DISPLAY}
            NVIDIA_VISIBLE_DEVICES: all
        runtime: nvidia
        volumes:
          - /tmp/.X11-unix:/tmp/.X11-unix:ro
 
    balloon_killer:
        image: vector_guidance/ros1:v1.0
        network_mode: "host"
        privileged: true
        command: bash -c "source /opt/ros/noetic/setup.bash && source /home/vg/vg_ws/devel/setup.bash && sleep 10 && rosrun balloon_intercept balloon_killer_node.py"
        environment:
            DISPLAY: ${DISPLAY}
            NVIDIA_VISIBLE_DEVICES: all
        runtime: nvidia
        volumes:
          - /tmp/.X11-unix:/tmp/.X11-unix:ro
